name: Extrair scripts.zip

on:
  push:
    paths:
      - "scripts.zip"

jobs:
  unzip-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extrair scripts.zip
        run: |
          unzip -o scripts.zip -d scripts

      - name: Commit e Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add scripts
          git commit -m "Extra√≠do scripts.zip"
          git push || echo "Nada para enviar"
